### ISSUE TITLE
icon compilation error

### ISSUE THREAD

**Issue by pixelpolisher** [stefspakman/Goat#29]
goatconfig.json
`"icons": {
    "fontName": "icons",
    "prefix": "icon",
    "fontDirectory": "fonts",
    "styles": {
      "filename": "style"
    },
    "generate": {
      "woff": true,
      "eot": false,
      "ttf": false,
      "woff2": true,
      "preview": true,
      "json": true,
      "variables": true,
      "css": true,
      "styles": true,
      "selection": true,
      "svg": true,
      "symbol": true
    }
  }`

error:
`TypeError: Cannot read property '0' of null
/Users/barthendrix/.nvm/versions/node/v12.16.1/lib/node_modules/@geit/goat/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var node

RuntimeError: abort(TypeError: Cannot read property '0' of null). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/barthendrix/.nvm/versions/node/v12.16.1/lib/node_modules/@geit/goat/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1:10832)
    at process.emit (events.js:311:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)`

**Comment by AubreyHewes** [comment]
@pixelpolisher can you reformat your code to be readable? (see github markdown help)

And then re-edit your issue to describe the actual problem that occurred and what you expected?
Include full configs (use the details html tag; see github documentation) (hide what is not relevant, home dir project dir customer dir etc)
